---
title: "Untitled"
output: html_document
---

```{r setup, include=True}
knitr::opts_chunk$set(echo = TRUE)
library(ezids)

setwd("C:/Users/Atharva/Desktop/George Washington University/DATS 6101/Midterm")
getwd()
midterm <- data.frame(read.csv("listings_with_reviews_price.csv"))
```

```{r cars}
library(ggplot2)
ggplot(midterm,aes(x=longitude, y=latitude,fill=price)) + geom_tile(lwd = 10,linetype = 1) +labs(title="Price for different areas",x="latitude", y = "Longitude",col.main="orange") + scale_fill_gradient2(limits=c(0,1000))


ggplot(midterm, aes(x = room_type, y = price)) + geom_boxplot(col = "red", fill = "blue",outlier.shape = NA)+  xlab("Room Type") + ylab("Price") +coord_cartesian(ylim = c(0,400))+ theme_bw(16, "serif") +theme(plot.title = element_text(size = rel(1.2), vjust = 1.5)) + ggtitle("Room type VS Price")


ggplot(midterm, aes(x = review_scores_rating, y = price)) + geom_boxplot(col = "red", fill = "blue",outlier.shape = NA)+  xlab("Room Type") + ylab("Price") +coord_cartesian(ylim = c(0,400))+ theme_bw(16, "serif") +theme(plot.title = element_text(size = rel(1.2), vjust = 1.5)) + ggtitle("Room type VS Price")

```

```{r pressure, echo=FALSE}


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
